import { Deal, Lead, CPQProductItem } from "./types";

export const INITIAL_DEALS: Deal[] = [
  {
    id: "deal-001",
    title: "Enterprise Revenue Cloud & Multi-Mall POS Sync",
    company: "SM Prime Holdings, Inc.",
    industry: "Real Estate & Commercial Retail",
    location: "Mall of Asia Complex, Pasay City",
    amount: 3200000,
    stage: "negotiation",
    probability: 85,
    owner: "Marco Dela Cruz (Sales Director)",
    contactName: "Engr. Rafael Santos",
    contactEmail: "r.santos@smprime.com",
    contactPhone: "+63 917 882 1920",
    expectedCloseDate: "2026-10-15",
    priority: "high",
    notes: "Executive committee approved technical pilot. Awaiting finalized CPQ volume discount sign-off.",
  },
  {
    id: "deal-002",
    title: "Proprietary Voice AI Collections & Telephony Core",
    company: "BDO Unibank Enterprise",
    industry: "Banking & Financial Services",
    location: "Makati CBD, Metro Manila",
    amount: 8900000,
    stage: "closed_won",
    probability: 100,
    owner: "Katrina Valdez (Senior Account Exec)",
    contactName: "Ma. Cristina Reyes",
    contactEmail: "reyes.cristina@bdo.com.ph",
    contactPhone: "+63 918 554 8831",
    expectedCloseDate: "2026-09-20",
    priority: "urgent",
    notes: "BSP compliance documentation verified. Multi-year enterprise license signed.",
  },
  {
    id: "deal-003",
    title: "Smart Property Management & Digital Tenant Lease Hub",
    company: "Ayala Land Corporation",
    industry: "Commercial Property",
    location: "Tower One, Ayala Triangle, Makati",
    amount: 4500000,
    stage: "proposal",
    probability: 60,
    owner: "Marco Dela Cruz (Sales Director)",
    contactName: "Juan Carlos Zobel-Tan",
    contactEmail: "jczobel@ayalaland.com.ph",
    contactPhone: "+63 917 119 4022",
    expectedCloseDate: "2026-11-01",
    priority: "high",
    notes: "Presented 1-click CPQ quoting. RFP technical matrix submitted.",
  },
  {
    id: "deal-004",
    title: "Omnichannel Logistics Dispatch & Fleet Routing",
    company: "Jollibee Foods Corporation",
    industry: "Food & QSR Supply Chain",
    location: "Ortigas Center, Pasig City",
    amount: 5100000,
    stage: "closed_won",
    probability: 100,
    owner: "Katrina Valdez (Senior Account Exec)",
    contactName: "David Lee",
    contactEmail: "david.lee@jfc.com.ph",
    contactPhone: "+63 920 901 3341",
    expectedCloseDate: "2026-08-30",
    priority: "high",
    notes: "Deployment across Luzon commissary hubs operational.",
  },
  {
    id: "deal-005",
    title: "AI Queue & Teller Management Integration",
    company: "Philippine National Bank",
    industry: "Banking & Finance",
    location: "Macapagal Blvd, Pasay City",
    amount: 4100000,
    stage: "qualified",
    probability: 45,
    owner: "Angelo Ramos (Account Exec)",
    contactName: "Grace Villanueva",
    contactEmail: "villanueva.g@pnb.com.ph",
    contactPhone: "+63 917 443 8901",
    expectedCloseDate: "2026-11-20",
    priority: "medium",
    notes: "Branch modernization POC scheduled for 10 Metro Manila branches.",
  },
  {
    id: "deal-006",
    title: "Sub-Second Inbound Lead Scoring & CRM Modernization",
    company: "Converge ICT Solutions",
    industry: "Telecommunications & Fiber",
    location: "Clark Freeport Zone & Pasig",
    amount: 3750000,
    stage: "lead_in",
    probability: 25,
    owner: "Angelo Ramos (Account Exec)",
    contactName: "Dennis Uy-Castillo",
    contactEmail: "dennis.castillo@convergeict.com",
    contactPhone: "+63 919 778 2309",
    expectedCloseDate: "2026-12-05",
    priority: "medium",
    notes: "Inbound inquiry from architecture call. Needs high-throughput API webhooks.",
  },
  {
    id: "deal-007",
    title: "Sports Venue Court Booking & Tournament Ladder",
    company: "The City Club Alphaland",
    industry: "Hospitality & Sports Arenas",
    location: "Ayala Avenue Extension, Makati",
    amount: 1450000,
    stage: "proposal",
    probability: 65,
    owner: "Marco Dela Cruz (Sales Director)",
    contactName: "Patricia Gomez",
    contactEmail: "pgomez@alphaland.com.ph",
    contactPhone: "+63 917 550 1199",
    expectedCloseDate: "2026-10-25",
    priority: "medium",
    notes: "Pickleball & squash court digital paddle rack demo scheduled next Tuesday.",
  },
  {
    id: "deal-008",
    title: "Enterprise Warehouse Barcode & RFID Ledger",
    company: "Robinsons Retail Holdings",
    industry: "Supply Chain & Retail Distribution",
    location: "Brgy. Ugong Norte, Quezon City",
    amount: 2400000,
    stage: "negotiation",
    probability: 80,
    owner: "Katrina Valdez (Senior Account Exec)",
    contactName: "Michael Go",
    contactEmail: "mgo@robinsonsretail.com.ph",
    contactPhone: "+63 918 332 5500",
    expectedCloseDate: "2026-10-18",
    priority: "high",
    notes: "Security and single sign-on review approved by IT Security.",
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: "lead-101",
    name: "Atty. Victoria Soriano",
    company: "Megaworld Corporation",
    title: "VP of Business Development",
    email: "v.soriano@megaworldcorp.com",
    phone: "+63 917 334 2200",
    location: "Uptown Bonifacio, Taguig",
    estimatedBudget: 3500000,
    aiScore: 96,
    scoreReason: "High executive seniority, confirmed budget authority, immediate Q4 deployment timeline.",
    source: "Architecture Consultation",
    status: "new",
    createdAt: "Today at 09:14 AM",
  },
  {
    id: "lead-102",
    name: "Engr. Ronald Mendoza",
    company: "DMCI Project Developers",
    title: "Director of Construction Tech",
    email: "rmendoza@dmcihomes.com",
    phone: "+63 918 440 9981",
    location: "Chino Roces Ave, Makati",
    estimatedBudget: 4200000,
    aiScore: 92,
    scoreReason: "Multi-jobsite tracking requirement, requested custom BIR CAS export compatibility.",
    source: "Web Inbound",
    status: "new",
    createdAt: "Yesterday at 04:30 PM",
  },
  {
    id: "lead-103",
    name: "Sarah Lim-Clemente",
    company: "Cebu Landmasters Inc.",
    title: "Head of Digital Operations",
    email: "slim@cebulandmasters.com",
    phone: "+63 917 662 1088",
    location: "Cebu IT Park, Cebu City",
    estimatedBudget: 2800000,
    aiScore: 88,
    scoreReason: "Visayas-Mindanao expansion plan, active search for CRM with offline mobile sync.",
    source: "Executive Referral",
    status: "contacted",
    createdAt: "2 days ago",
  },
  {
    id: "lead-104",
    name: "Kenneth Tan",
    company: "Century Pacific Food, Inc.",
    title: "Supply Chain Solutions Architect",
    email: "ktan@centurypacific.com.ph",
    phone: "+63 920 119 5543",
    location: "Centerpoint Bldg, Ortigas Center",
    estimatedBudget: 5000000,
    aiScore: 94,
    scoreReason: "Large-scale distributor network integration, urgent DOLE & logistics compliance.",
    source: "Architecture Consultation",
    status: "qualified",
    createdAt: "3 days ago",
  },
];

export const CPQ_CATALOG: CPQProductItem[] = [
  {
    id: "cpq-core-crm",
    name: "BITScrm Enterprise Core Platform",
    description: "Unlimited pipelines, visual Kanban, AI deal velocity scoring, custom fields & REST API.",
    monthlyPerSeat: 1850,
    selected: true,
    quantity: 25,
  },
  {
    id: "cpq-cpq-engine",
    name: "1-Click CPQ & Dynamic Quoting Module",
    description: "Multi-currency (₱ PHP / $ USD), discount guardrails, and automated PDF quote generation.",
    monthlyPerSeat: 850,
    selected: true,
    quantity: 25,
  },
  {
    id: "cpq-voice-ai",
    name: "BITSagent Sub-300ms Voice AI Dialer Add-on",
    description: "BSP-compliant debt recovery & lead qualification voice assistant with zero hallucinations.",
    monthlyPerSeat: 2400,
    selected: false,
    quantity: 10,
  },
  {
    id: "cpq-sla-support",
    name: "24/7 Manila Priority SLA & Dedicated TAM",
    description: "Sub-15 minute P1 emergency response, dedicated Technical Account Manager, and custom onboarding.",
    monthlyPerSeat: 0,
    annualFlatPrice: 350000,
    selected: true,
    quantity: 1,
  },
];
