import type { CrmState } from "./types";

export const seedCrmState = (): CrmState => ({
  companies: [
    {
      id: "co-1",
      name: "EastWest Credit & Recovery Solutions",
      domain: "eastwestcredit.ph",
      industry: "Banking & Consumer Finance",
      employees: 240,
      arrEstimate: 1_450_000,
      owner: "Malcolm Cuady",
      location: "Ortigas Center, Pasig City",
    },
    {
      id: "co-2",
      name: "Maya Bank / Voyager Innovations",
      domain: "voyager.ph",
      industry: "Digital Banking & FinTech",
      employees: 650,
      arrEstimate: 920_000,
      owner: "Rina Velasco",
      location: "Mandaluyong, Metro Manila",
    },
    {
      id: "co-3",
      name: "Sutherland Global Services BPO",
      domain: "sutherlandbpo.com",
      industry: "BPO & Omnichannel Contact Center",
      employees: 1800,
      arrEstimate: 2_100_000,
      owner: "Malcolm Cuady",
      location: "BGC, Taguig City",
    },
    {
      id: "co-4",
      name: "SeaMoney / ShopeePay Philippines",
      domain: "seamoney.ph",
      industry: "E-Commerce & BNPL Lending",
      employees: 420,
      arrEstimate: 1_650_000,
      owner: "Aya Mendoza",
      location: "Pasig City, Metro Manila",
    },
    {
      id: "co-5",
      name: "Insular Life Health Care (InLife)",
      domain: "inlife.com.ph",
      industry: "Insurance & Healthcare",
      employees: 310,
      arrEstimate: 780_000,
      owner: "Jonas Park",
      location: "Makati City, Metro Manila",
    },
    {
      id: "co-6",
      name: "Fast Logistics Manila Cargo Hub",
      domain: "fastlogistics.com.ph",
      industry: "Supply Chain & Logistics",
      employees: 540,
      arrEstimate: 1_250_000,
      owner: "Malcolm Cuady",
      location: "Paranaque, Metro Manila",
    },
    {
      id: "co-7",
      name: "Advance Credit Tech FinTech",
      domain: "advancecredit.io",
      industry: "FinTech & Salary Lending",
      employees: 85,
      arrEstimate: 880_000,
      owner: "Malcolm Cuady",
      location: "Makati City, Metro Manila",
    },
  ],
  contacts: [
    {
      id: "ct-1",
      name: "Atty. Rafael Dizon",
      email: "r.dizon@eastwestcredit.ph",
      phone: "+63 917 552 1190",
      title: "VP Legal & Collections",
      companyId: "co-1",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-24T18:45:00Z",
      tags: ["decision-maker", "bsp-compliance", "website-lead"],
    },
    {
      id: "ct-2",
      name: "Patricia Reyes",
      email: "patricia.reyes@voyager.ph",
      phone: "+63 918 220 8844",
      title: "Head of Merchant Risk",
      companyId: "co-2",
      owner: "Rina Velasco",
      lastTouchAt: "2026-09-24T16:20:00Z",
      tags: ["webhook-engineer", "fintech", "website-lead"],
    },
    {
      id: "ct-3",
      name: "Marcus Sterling",
      email: "msterling@sutherlandbpo.com",
      phone: "+63 919 441 3320",
      title: "Vice President of Operations",
      companyId: "co-3",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-24T14:10:00Z",
      tags: ["bpo-floor", "ai-voice", "specimen-lead"],
    },
    {
      id: "ct-4",
      name: "Bea Villaruel",
      email: "bea.villaruel@seamoney.ph",
      phone: "+63 920 882 1140",
      title: "Head of Customer Recovery",
      companyId: "co-4",
      owner: "Aya Mendoza",
      lastTouchAt: "2026-09-23T19:30:00Z",
      tags: ["bnpl", "staging-queues", "website-lead"],
    },
    {
      id: "ct-5",
      name: "Carlos Tan",
      email: "ctan@inlife.com.ph",
      phone: "+63 917 884 5511",
      title: "IT Systems Director",
      companyId: "co-5",
      owner: "Jonas Park",
      lastTouchAt: "2026-09-23T11:45:00Z",
      tags: ["private-cloud", "support-hud"],
    },
    {
      id: "ct-6",
      name: "Eduardo Gomez",
      email: "e.gomez@fastlogistics.com.ph",
      phone: "+63 918 771 9920",
      title: "Logistics Operations Director",
      companyId: "co-6",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-22T08:15:00Z",
      tags: ["erp-integration", "dispatch"],
    },
    {
      id: "ct-7",
      name: "Michelle Co",
      email: "mco@advancecredit.io",
      phone: "+63 921 330 6670",
      title: "Managing Partner",
      companyId: "co-7",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-21T15:00:00Z",
      tags: ["white-label", "partner-inquiry"],
    },
  ],
  leads: [
    {
      id: "ld-1",
      name: "Atty. Rafael Dizon",
      email: "r.dizon@eastwestcredit.ph",
      company: "EastWest Credit & Recovery Solutions",
      title: "VP Legal & Collections",
      source: "Website Contact Form",
      status: "new",
      score: 96,
      owner: "Malcolm Cuady",
      createdAt: "2026-09-24T18:45:00Z",
      lastActivityAt: "2026-09-24T18:45:00Z",
      notes: "Inquired via Contact Form. Operates 150-seat recovery floor. Needs WebRTC predictive dialer, GCash tokenized links, and automated BSP 454 quiet hours (6 AM - 10 PM).",
    },
    {
      id: "ld-2",
      name: "Patricia Reyes",
      email: "patricia.reyes@voyager.ph",
      company: "Maya Bank / Voyager Innovations",
      title: "Head of Merchant Risk",
      source: "Website Contact Form",
      status: "working",
      score: 94,
      owner: "Rina Velasco",
      createdAt: "2026-09-24T16:20:00Z",
      lastActivityAt: "2026-09-24T16:20:00Z",
      notes: "Inquired via Contact Form. Evaluating settlement webhook engine to credit incoming Maya/GCash debtor repayments in sub-2s. Technical architecture review pending.",
    },
    {
      id: "ld-3",
      name: "Marcus Sterling",
      email: "msterling@sutherlandbpo.com",
      company: "Sutherland Global Services BPO",
      title: "Vice President of Operations",
      source: "BITScrm Interactive Specimen",
      status: "qualified",
      score: 98,
      owner: "Malcolm Cuady",
      createdAt: "2026-09-24T14:10:00Z",
      lastActivityAt: "2026-09-24T14:10:00Z",
      notes: "Submitted through interactive CRM specimen. Wants BITSagent AI voice agents to automate 40,000 low-balance debtor accounts (< ₱15,000) with supervisor warm-transfer.",
    },
    {
      id: "ld-4",
      name: "Bea Villaruel",
      email: "bea.villaruel@seamoney.ph",
      company: "SeaMoney / ShopeePay Philippines",
      title: "Head of Customer Recovery",
      source: "Website Contact Form",
      status: "working",
      score: 91,
      owner: "Aya Mendoza",
      createdAt: "2026-09-23T19:30:00Z",
      lastActivityAt: "2026-09-23T19:30:00Z",
      notes: "Inquired via Contact Form. Requires dynamic staging queues (1-30, 31-60 DPD) and automated morning requeue for broken Promise-to-Pay arrangements.",
    },
    {
      id: "ld-5",
      name: "Carlos Tan",
      email: "ctan@inlife.com.ph",
      company: "Insular Life Health Care (InLife)",
      title: "IT Systems Director",
      source: "White-Label Partner Consultation",
      status: "new",
      score: 88,
      owner: "Jonas Park",
      createdAt: "2026-09-23T11:45:00Z",
      lastActivityAt: "2026-09-23T11:45:00Z",
      notes: "Inquired via White-Label Form. Looking for sovereign on-premise deployment of BITScrm Support to reduce annual Salesforce seat licensing by 60%.",
    },
    {
      id: "ld-6",
      name: "Eduardo Gomez",
      email: "e.gomez@fastlogistics.com.ph",
      company: "Fast Logistics Manila Cargo Hub",
      title: "Logistics Operations Director",
      source: "Website Contact Form",
      status: "qualified",
      score: 89,
      owner: "Malcolm Cuady",
      createdAt: "2026-09-22T08:15:00Z",
      lastActivityAt: "2026-09-22T08:15:00Z",
      notes: "Inquired via Contact Form. Wants BITS Core ERP dispatch & fleet integration to give support agents real-time visibility over delayed regional shipping containers.",
    },
    {
      id: "ld-7",
      name: "Michelle Co",
      email: "mco@advancecredit.io",
      company: "Advance Credit Tech FinTech",
      title: "Managing Partner",
      source: "White-Label Partner Consultation",
      status: "working",
      score: 85,
      owner: "Malcolm Cuady",
      createdAt: "2026-09-21T15:00:00Z",
      lastActivityAt: "2026-09-21T15:00:00Z",
      notes: "Inquired via White-Label Form. Evaluating BITS White-Label Deployment to offer embedded employee loan & debt recovery portal under Advance brand.",
    },
  ],
  pipelines: [
    {
      id: "pl-1",
      name: "BITS Commercial Pipeline",
      stages: [
        { id: "discovery", label: "Discovery Scheduled", order: 1 },
        { id: "proposal", label: "Architecture Proposal", order: 2 },
        { id: "negotiation", label: "Commercial Terms", order: 3 },
        { id: "closed_won", label: "Contract Executed", order: 4 },
        { id: "closed_lost", label: "Disqualified / Closed Lost", order: 5 },
      ],
    },
  ],
  opportunities: [
    {
      id: "op-1",
      name: "EastWest Credit — 150-Seat Collections CRM",
      companyId: "co-1",
      contactId: "ct-1",
      stage: "negotiation",
      amount: 1_450_000,
      probability: 75,
      closeDate: "2026-10-15",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
      stalledDays: 3,
    },
    {
      id: "op-2",
      name: "Sutherland BPO — BITSagent AI Voice Automation",
      companyId: "co-3",
      contactId: "ct-3",
      stage: "proposal",
      amount: 2_100_000,
      probability: 60,
      closeDate: "2026-10-31",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
    },
    {
      id: "op-3",
      name: "SeaMoney PH — Staging Queues & PTP Engine",
      companyId: "co-4",
      contactId: "ct-4",
      stage: "proposal",
      amount: 1_650_000,
      probability: 55,
      closeDate: "2026-11-15",
      owner: "Aya Mendoza",
      pipelineId: "pl-1",
    },
    {
      id: "op-4",
      name: "Maya Bank — Settlement Webhook Bridge",
      companyId: "co-2",
      contactId: "ct-2",
      stage: "discovery",
      amount: 920_000,
      probability: 40,
      closeDate: "2026-11-30",
      owner: "Rina Velasco",
      pipelineId: "pl-1",
    },
    {
      id: "op-5",
      name: "Fast Logistics — BITS Core ERP Manila",
      companyId: "co-6",
      contactId: "ct-6",
      stage: "closed_won",
      amount: 1_250_000,
      probability: 100,
      closeDate: "2026-09-18",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
    },
    {
      id: "op-6",
      name: "Advance Credit — White-Label CRM Program",
      companyId: "co-7",
      contactId: "ct-7",
      stage: "negotiation",
      amount: 880_000,
      probability: 70,
      closeDate: "2026-10-20",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
      stalledDays: 5,
    },
    {
      id: "op-7",
      name: "InLife Health — Omnichannel Support SLA",
      companyId: "co-5",
      contactId: "ct-5",
      stage: "discovery",
      amount: 780_000,
      probability: 35,
      closeDate: "2026-12-05",
      owner: "Jonas Park",
      pipelineId: "pl-1",
    },
  ],
  tasks: [
    {
      id: "tk-1",
      title: "Deliver WebRTC predictive dialer test credentials to Atty. Dizon",
      relatedType: "opportunity",
      relatedId: "op-1",
      relatedLabel: "EastWest Credit — 150-Seat Collections CRM",
      dueAt: "2026-09-25T17:00:00Z",
      status: "open",
      owner: "Malcolm Cuady",
      priority: "high",
    },
    {
      id: "tk-2",
      title: "Provide JSON payload spec for Maya settlement webhook",
      relatedType: "opportunity",
      relatedId: "op-4",
      relatedLabel: "Maya Bank — Settlement Webhook Bridge",
      dueAt: "2026-09-26T10:00:00Z",
      status: "open",
      owner: "Rina Velasco",
      priority: "medium",
    },
    {
      id: "tk-3",
      title: "Schedule BITSagent natural voice demonstration for Sutherland BPO leadership",
      relatedType: "opportunity",
      relatedId: "op-2",
      relatedLabel: "Sutherland BPO — BITSagent AI Voice Automation",
      dueAt: "2026-09-25T14:00:00Z",
      status: "open",
      owner: "Malcolm Cuady",
      priority: "high",
    },
    {
      id: "tk-4",
      title: "Qualify inbound Contact Form submission from Atty. Rafael Dizon",
      relatedType: "lead",
      relatedId: "ld-1",
      relatedLabel: "Atty. Rafael Dizon",
      dueAt: "2026-09-25T09:00:00Z",
      status: "open",
      owner: "Malcolm Cuady",
      priority: "high",
    },
    {
      id: "tk-5",
      title: "Finalize deployment handbook for Fast Logistics ERP pilot",
      relatedType: "opportunity",
      relatedId: "op-5",
      relatedLabel: "Fast Logistics — BITS Core ERP Manila",
      dueAt: "2026-09-20T16:00:00Z",
      status: "done",
      owner: "Malcolm Cuady",
      priority: "low",
    },
  ],
  conversations: [
    {
      id: "cv-1",
      subject: "Inquiry: BSP 454 quiet hour enforcement & predictive softphone demo",
      contactName: "Atty. Rafael Dizon",
      contactEmail: "r.dizon@eastwestcredit.ph",
      channel: "email",
      unread: true,
      updatedAt: "2026-09-24T18:45:00Z",
      messages: [
        {
          id: "m1",
          channel: "email",
          direction: "inbound",
          body: "We operate a 150-seat recovery floor in Ortigas handling credit card recoveries. We need automated right-party connect detection, strict 6 AM - 10 PM contact enforcement, and GCash/Maya tokenized payment links. When can we schedule a technical walkthrough?",
          at: "2026-09-24T18:45:00Z",
        },
      ],
    },
    {
      id: "cv-2",
      subject: "Technical specs for settlement webhook callback URL",
      contactName: "Patricia Reyes",
      contactEmail: "patricia.reyes@voyager.ph",
      channel: "email",
      unread: false,
      updatedAt: "2026-09-24T16:20:00Z",
      messages: [
        {
          id: "m2",
          channel: "email",
          direction: "inbound",
          body: "Hello BITS RevOps Team — Inquiring about deploying your settlement webhook engine to credit incoming payments directly to debtor accounts within 2 seconds. Also exploring your white-label contact center capabilities.",
          at: "2026-09-24T16:20:00Z",
        },
        {
          id: "m3",
          channel: "email",
          direction: "outbound",
          body: "Hi Patricia, thanks for reaching out via our consultation form. Attached is the OpenAPI 3.1 specification for our idempotent settlement webhook bridge with HMAC-SHA256 signature verification.",
          at: "2026-09-24T17:15:00Z",
        },
      ],
    },
    {
      id: "cv-3",
      subject: "Request for BITSagent AI speech latency benchmarking (<300ms)",
      contactName: "Marcus Sterling",
      contactEmail: "msterling@sutherlandbpo.com",
      channel: "email",
      unread: false,
      updatedAt: "2026-09-24T14:10:00Z",
      messages: [
        {
          id: "m4",
          channel: "email",
          direction: "inbound",
          body: "Marcus from Sutherland BPO here. We tested the interactive specimen on your website and were impressed with the response cadence. Can we stress-test 100 concurrent SIP calls to verify speech recognition under Tagalog/English code-switching?",
          at: "2026-09-24T14:10:00Z",
        },
      ],
    },
  ],
  campaigns: [
    {
      id: "cp-1",
      name: "BSP Compliance & Collections AI Nurture",
      channel: "Email",
      status: "active",
      sent: 2420,
      opens: 1140,
      clicks: 412,
      conversions: 68,
      owner: "Aya Mendoza",
    },
    {
      id: "cp-2",
      name: "Predictive Dialer Interactive Calculator",
      channel: "Website Specimen + SMS",
      status: "completed",
      sent: 1250,
      opens: 680,
      clicks: 290,
      conversions: 84,
      owner: "Malcolm Cuady",
    },
    {
      id: "cp-3",
      name: "White-Label Partner Invitation Deck",
      channel: "Direct Email",
      status: "active",
      sent: 340,
      opens: 180,
      clicks: 72,
      conversions: 14,
      owner: "Malcolm Cuady",
    },
  ],
  automations: [
    {
      id: "au-1",
      name: "Website Form Submission → Auto-Qualify & Assign AE",
      trigger: "New Contact Form Submission",
      status: "active",
      runs30d: 218,
      successRate: 0.99,
    },
    {
      id: "au-2",
      name: "High-Intent Lead (Score ≥ 90) → Instant SMS Alert to Floor",
      trigger: "Lead Score ≥ 90",
      status: "active",
      runs30d: 46,
      successRate: 1.0,
    },
    {
      id: "au-3",
      name: "Broken PTP Arrangement → Automated Morning Requeue",
      trigger: "Promise-to-Pay Default",
      status: "active",
      runs30d: 312,
      successRate: 0.98,
    },
  ],
  funnels: [
    {
      id: "fn-1",
      name: "Website Inbound Lead Funnel",
      status: "live",
      conversionRate: 0.048,
      steps: [
        { label: "Homepage & Solutions Visits", visitors: 6400 },
        { label: "Product Specimen & Features", visitors: 3150 },
        { label: "Website Contact Form Opened", visitors: 820 },
        { label: "Consultation Booked & Qualified", visitors: 394 },
      ],
    },
    {
      id: "fn-2",
      name: "White-Label Partner Funnel",
      status: "live",
      conversionRate: 0.021,
      steps: [
        { label: "White-Label Page Visits", visitors: 1850 },
        { label: "Partner Deck Downloaded", visitors: 640 },
        { label: "Partner Consultation Form Submitted", visitors: 38 },
      ],
    },
  ],
  forms: [
    {
      id: "fm-1",
      name: "BITS Website Contact & Consultation Form (/#contact)",
      submissions30d: 24,
      conversionRate: 0.048,
      fields: 9,
      status: "published",
    },
    {
      id: "fm-2",
      name: "BITScrm Interactive Specimen Action Form (/bitscrm)",
      submissions30d: 42,
      conversionRate: 0.124,
      fields: 4,
      status: "published",
    },
    {
      id: "fm-3",
      name: "White-Label Software Program Consultation (/products/white-label)",
      submissions30d: 8,
      conversionRate: 0.021,
      fields: 8,
      status: "published",
    },
  ],
  templates: [
    {
      id: "tp-1",
      name: "BSP 454 Compliance & Dialer Walkthrough",
      channel: "email",
      category: "Sales",
      updatedAt: "2026-09-22",
      usage30d: 74,
    },
    {
      id: "tp-2",
      name: "Tokenized Settlement Webhook API Documentation",
      channel: "email",
      category: "Technical",
      updatedAt: "2026-09-20",
      usage30d: 38,
    },
    {
      id: "tp-3",
      name: "Immediate Inbound Inquiry Auto-Acknowledgment",
      channel: "email",
      category: "Operations",
      updatedAt: "2026-09-24",
      usage30d: 112,
    },
  ],
  team: [
    {
      id: "tm-0",
      name: "Malcolm Cuady",
      email: "demo@boundlessitsolutions.com",
      role: "Admin",
      openDeals: 4,
      closedWon30d: 1_250_000,
    },
    {
      id: "tm-1",
      name: "Malcolm Cuady (Primary)",
      email: "malcolm@boundlessitsolutions.com",
      role: "Admin",
      openDeals: 4,
      closedWon30d: 1_250_000,
    },
    {
      id: "tm-2",
      name: "Rina Velasco",
      email: "rina@boundlessits.com",
      role: "Manager",
      openDeals: 1,
      closedWon30d: 0,
    },
    {
      id: "tm-3",
      name: "Jonas Park",
      email: "jonas@boundlessits.com",
      role: "Rep",
      openDeals: 1,
      closedWon30d: 0,
    },
    {
      id: "tm-4",
      name: "Aya Mendoza",
      email: "aya@boundlessits.com",
      role: "Marketing",
      openDeals: 1,
      closedWon30d: 0,
    },
  ],
  activities: [
    {
      id: "ac-1",
      type: "note",
      summary: "Inbound form submission: Atty. Rafael Dizon (EastWest Credit) requested 150-seat dialer walkthrough",
      actor: "Website Contact Form",
      at: "2026-09-24T18:45:00Z",
    },
    {
      id: "ac-2",
      type: "note",
      summary: "Technical inquiry: Patricia Reyes (Maya Bank) requested settlement webhook documentation",
      actor: "Website Contact Form",
      at: "2026-09-24T16:20:00Z",
    },
    {
      id: "ac-3",
      type: "stage",
      summary: "Opportunity moved: Sutherland Global BPO → Architecture Proposal (₱2.1M)",
      actor: "Malcolm Cuady",
      at: "2026-09-24T14:10:00Z",
    },
    {
      id: "ac-4",
      type: "call",
      summary: "Discovery call completed with Bea Villaruel (SeaMoney PH) on BNPL staging queues",
      actor: "Aya Mendoza",
      at: "2026-09-23T19:30:00Z",
    },
    {
      id: "ac-5",
      type: "email",
      summary: "Dispatched White-Label Architecture Briefing to Michelle Co (Advance Credit Tech)",
      actor: "Malcolm Cuady",
      at: "2026-09-21T15:00:00Z",
    },
  ],
});
