import type { CrmState } from "./types";

export const seedCrmState = (): CrmState => ({
  companies: [
    {
      id: "co-1",
      name: "Harborline Logistics",
      domain: "harborline.io",
      industry: "Logistics",
      employees: 420,
      arrEstimate: 1_850_000,
      owner: "Malcolm Cuady",
      location: "Manila, PH",
    },
    {
      id: "co-2",
      name: "Northwind Clinics",
      domain: "northwind.health",
      industry: "Healthcare",
      employees: 180,
      arrEstimate: 960_000,
      owner: "Rina Velasco",
      location: "Cebu, PH",
    },
    {
      id: "co-3",
      name: "Voltgrid Energy",
      domain: "voltgrid.energy",
      industry: "Energy",
      employees: 95,
      arrEstimate: 640_000,
      owner: "Jonas Park",
      location: "Singapore",
    },
    {
      id: "co-4",
      name: "Brightpath Schools",
      domain: "brightpath.edu",
      industry: "Education",
      employees: 310,
      arrEstimate: 1_120_000,
      owner: "Aya Mendoza",
      location: "Quezon City, PH",
    },
    {
      id: "co-5",
      name: "Cedar & Co Retail",
      domain: "cedar.co",
      industry: "Retail",
      employees: 1_200,
      arrEstimate: 2_400_000,
      owner: "Malcolm Cuady",
      location: "Makati, PH",
    },
  ],
  contacts: [
    {
      id: "ct-1",
      name: "Elise Navarro",
      email: "elise@harborline.io",
      phone: "+63 917 442 1180",
      title: "VP Operations",
      companyId: "co-1",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-10T09:20:00Z",
      tags: ["decision-maker", "ops"],
    },
    {
      id: "ct-2",
      name: "Dr. Marcus Chen",
      email: "m.chen@northwind.health",
      phone: "+63 918 220 4411",
      title: "CIO",
      companyId: "co-2",
      owner: "Rina Velasco",
      lastTouchAt: "2026-09-09T14:05:00Z",
      tags: ["champion"],
    },
    {
      id: "ct-3",
      name: "Priya Sundaram",
      email: "priya@voltgrid.energy",
      phone: "+65 8123 4402",
      title: "Head of Digital",
      companyId: "co-3",
      owner: "Jonas Park",
      lastTouchAt: "2026-09-08T11:40:00Z",
      tags: ["procurement"],
    },
    {
      id: "ct-4",
      name: "Leo Santos",
      email: "leo@brightpath.edu",
      phone: "+63 919 771 2033",
      title: "IT Director",
      companyId: "co-4",
      owner: "Aya Mendoza",
      lastTouchAt: "2026-09-11T08:15:00Z",
      tags: ["budget-owner"],
    },
    {
      id: "ct-5",
      name: "Hannah Ortiz",
      email: "hannah@cedar.co",
      phone: "+63 920 115 8890",
      title: "CX Lead",
      companyId: "co-5",
      owner: "Malcolm Cuady",
      lastTouchAt: "2026-09-07T16:30:00Z",
      tags: ["influencer"],
    },
  ],
  leads: [
    {
      id: "ld-1",
      name: "Kai Rivera",
      email: "kai.rivera@meridianbank.ph",
      company: "Meridian Bank",
      title: "Digital Channels Manager",
      source: "Webinar",
      status: "working",
      score: 78,
      owner: "Rina Velasco",
      createdAt: "2026-09-02T04:00:00Z",
      lastActivityAt: "2026-09-11T10:00:00Z",
      notes: "Asked about omnichannel inbox SLA reporting.",
    },
    {
      id: "ld-2",
      name: "Sofia Lim",
      email: "sofia.lim@atlasfreight.com",
      company: "Atlas Freight",
      title: "COO",
      source: "Inbound form",
      status: "qualified",
      score: 91,
      owner: "Malcolm Cuady",
      createdAt: "2026-08-28T06:30:00Z",
      lastActivityAt: "2026-09-10T13:20:00Z",
      notes: "Wants BPO overflow for peak season.",
    },
    {
      id: "ld-3",
      name: "Noah Greer",
      email: "noah@clearwater.insure",
      company: "Clearwater Insurance",
      title: "Claims Ops Lead",
      source: "Partner referral",
      status: "new",
      score: 54,
      owner: "Jonas Park",
      createdAt: "2026-09-09T02:10:00Z",
      lastActivityAt: "2026-09-09T02:10:00Z",
      notes: "First touch pending.",
    },
    {
      id: "ld-4",
      name: "Mina Torres",
      email: "mina@lumenretail.asia",
      company: "Lumen Retail",
      title: "Marketing Ops",
      source: "LinkedIn",
      status: "working",
      score: 66,
      owner: "Aya Mendoza",
      createdAt: "2026-09-05T09:00:00Z",
      lastActivityAt: "2026-09-08T17:45:00Z",
      notes: "Interested in campaign automation templates.",
    },
    {
      id: "ld-5",
      name: "Victor Ong",
      email: "v.ong@pacificsteel.com",
      company: "Pacific Steel",
      title: "Plant IT Manager",
      source: "Trade show",
      status: "disqualified",
      score: 22,
      owner: "Jonas Park",
      createdAt: "2026-08-20T03:00:00Z",
      lastActivityAt: "2026-08-30T11:00:00Z",
      notes: "Budget frozen through Q4.",
    },
  ],
  pipelines: [
    {
      id: "pl-1",
      name: "Enterprise new business",
      stages: [
        { id: "discovery", label: "Discovery", order: 1 },
        { id: "proposal", label: "Proposal", order: 2 },
        { id: "negotiation", label: "Negotiation", order: 3 },
        { id: "closed_won", label: "Closed won", order: 4 },
        { id: "closed_lost", label: "Closed lost", order: 5 },
      ],
    },
  ],
  opportunities: [
    {
      id: "op-1",
      name: "Harborline omnichannel desk",
      companyId: "co-1",
      contactId: "ct-1",
      stage: "negotiation",
      amount: 186_000,
      probability: 65,
      closeDate: "2026-09-30",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
      stalledDays: 4,
    },
    {
      id: "op-2",
      name: "Northwind patient intake AI",
      companyId: "co-2",
      contactId: "ct-2",
      stage: "proposal",
      amount: 124_500,
      probability: 45,
      closeDate: "2026-10-15",
      owner: "Rina Velasco",
      pipelineId: "pl-1",
    },
    {
      id: "op-3",
      name: "Voltgrid field ops CRM",
      companyId: "co-3",
      contactId: "ct-3",
      stage: "discovery",
      amount: 78_000,
      probability: 25,
      closeDate: "2026-11-01",
      owner: "Jonas Park",
      pipelineId: "pl-1",
      stalledDays: 12,
    },
    {
      id: "op-4",
      name: "Brightpath enrollment funnel",
      companyId: "co-4",
      contactId: "ct-4",
      stage: "proposal",
      amount: 92_000,
      probability: 40,
      closeDate: "2026-10-08",
      owner: "Aya Mendoza",
      pipelineId: "pl-1",
    },
    {
      id: "op-5",
      name: "Cedar CX automation",
      companyId: "co-5",
      contactId: "ct-5",
      stage: "closed_won",
      amount: 210_000,
      probability: 100,
      closeDate: "2026-08-22",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
    },
    {
      id: "op-6",
      name: "Harborline SMS overflow",
      companyId: "co-1",
      contactId: "ct-1",
      stage: "closed_lost",
      amount: 48_000,
      probability: 0,
      closeDate: "2026-08-05",
      owner: "Malcolm Cuady",
      pipelineId: "pl-1",
    },
  ],
  tasks: [
    {
      id: "tk-1",
      title: "Send revised SLA addendum",
      relatedType: "opportunity",
      relatedId: "op-1",
      relatedLabel: "Harborline omnichannel desk",
      dueAt: "2026-09-11T17:00:00Z",
      status: "open",
      owner: "Malcolm Cuady",
      priority: "high",
    },
    {
      id: "tk-2",
      title: "Schedule clinical workflow demo",
      relatedType: "opportunity",
      relatedId: "op-2",
      relatedLabel: "Northwind patient intake AI",
      dueAt: "2026-09-13T09:00:00Z",
      status: "open",
      owner: "Rina Velasco",
      priority: "medium",
    },
    {
      id: "tk-3",
      title: "Re-engage stalled discovery",
      relatedType: "opportunity",
      relatedId: "op-3",
      relatedLabel: "Voltgrid field ops CRM",
      dueAt: "2026-09-10T12:00:00Z",
      status: "open",
      owner: "Jonas Park",
      priority: "high",
    },
    {
      id: "tk-4",
      title: "Qualify Meridian Bank lead",
      relatedType: "lead",
      relatedId: "ld-1",
      relatedLabel: "Kai Rivera",
      dueAt: "2026-09-14T10:00:00Z",
      status: "open",
      owner: "Rina Velasco",
      priority: "medium",
    },
    {
      id: "tk-5",
      title: "Log Cedar kickoff notes",
      relatedType: "opportunity",
      relatedId: "op-5",
      relatedLabel: "Cedar CX automation",
      dueAt: "2026-09-01T16:00:00Z",
      status: "done",
      owner: "Malcolm Cuady",
      priority: "low",
    },
  ],
  conversations: [
    {
      id: "cv-1",
      subject: "SLA draft for omnichannel desk",
      contactName: "Elise Navarro",
      contactEmail: "elise@harborline.io",
      channel: "email",
      unread: true,
      updatedAt: "2026-09-11T08:40:00Z",
      messages: [
        {
          id: "m1",
          channel: "email",
          direction: "outbound",
          body: "Elise — attached is the revised SLA with 24/7 SMS coverage and weekend escalation paths.",
          at: "2026-09-10T15:20:00Z",
        },
        {
          id: "m2",
          channel: "email",
          direction: "inbound",
          body: "Thanks. Can we tighten first-response to under 2 minutes for VIP queues?",
          at: "2026-09-11T08:40:00Z",
        },
      ],
    },
    {
      id: "cv-2",
      subject: "Demo follow-up",
      contactName: "Dr. Marcus Chen",
      contactEmail: "m.chen@northwind.health",
      channel: "email",
      unread: false,
      updatedAt: "2026-09-09T14:05:00Z",
      messages: [
        {
          id: "m3",
          channel: "email",
          direction: "outbound",
          body: "Recording and intake workflow diagrams from yesterday's session.",
          at: "2026-09-09T14:05:00Z",
        },
      ],
    },
    {
      id: "cv-3",
      subject: "SMS: enrollment reminder test",
      contactName: "Leo Santos",
      contactEmail: "leo@brightpath.edu",
      channel: "sms",
      unread: false,
      updatedAt: "2026-09-08T07:22:00Z",
      messages: [
        {
          id: "m4",
          channel: "sms",
          direction: "outbound",
          body: "Brightpath: your enrollment checklist is ready. Reply YES to get the link.",
          at: "2026-09-08T07:20:00Z",
        },
        {
          id: "m5",
          channel: "sms",
          direction: "inbound",
          body: "YES",
          at: "2026-09-08T07:22:00Z",
        },
      ],
    },
  ],
  campaigns: [
    {
      id: "cp-1",
      name: "Q3 Ops leaders nurture",
      channel: "Email",
      status: "active",
      sent: 1840,
      opens: 742,
      clicks: 216,
      conversions: 38,
      owner: "Aya Mendoza",
    },
    {
      id: "cp-2",
      name: "Healthcare AI webinar invite",
      channel: "Email + SMS",
      status: "completed",
      sent: 960,
      opens: 510,
      clicks: 188,
      conversions: 64,
      owner: "Rina Velasco",
    },
    {
      id: "cp-3",
      name: "Retail peak-season overflow",
      channel: "LinkedIn",
      status: "paused",
      sent: 420,
      opens: 0,
      clicks: 54,
      conversions: 9,
      owner: "Malcolm Cuady",
    },
  ],
  automations: [
    {
      id: "au-1",
      name: "Lead score ≥ 70 → assign AE",
      trigger: "Lead score updated",
      status: "active",
      runs30d: 142,
      successRate: 0.97,
    },
    {
      id: "au-2",
      name: "Stalled deal > 10 days alert",
      trigger: "Opportunity stage age",
      status: "active",
      runs30d: 28,
      successRate: 1,
    },
    {
      id: "au-3",
      name: "Form submit → welcome sequence",
      trigger: "Form submission",
      status: "paused",
      runs30d: 0,
      successRate: 0.94,
    },
  ],
  funnels: [
    {
      id: "fn-1",
      name: "Consultation booking",
      status: "live",
      conversionRate: 0.084,
      steps: [
        { label: "Landing", visitors: 4200 },
        { label: "Solutions", visitors: 2100 },
        { label: "Contact form", visitors: 680 },
        { label: "Booked", visitors: 352 },
      ],
    },
    {
      id: "fn-2",
      name: "Webinar registration",
      status: "live",
      conversionRate: 0.162,
      steps: [
        { label: "Invite open", visitors: 3100 },
        { label: "Landing", visitors: 1480 },
        { label: "Registered", visitors: 502 },
      ],
    },
  ],
  forms: [
    {
      id: "fm-1",
      name: "Book a consultation",
      submissions30d: 128,
      conversionRate: 0.31,
      fields: 6,
      status: "published",
    },
    {
      id: "fm-2",
      name: "Webinar RSVP",
      submissions30d: 214,
      conversionRate: 0.44,
      fields: 4,
      status: "published",
    },
    {
      id: "fm-3",
      name: "Partner inquiry (draft)",
      submissions30d: 0,
      conversionRate: 0,
      fields: 8,
      status: "draft",
    },
  ],
  templates: [
    {
      id: "tp-1",
      name: "Discovery follow-up",
      channel: "email",
      category: "Sales",
      updatedAt: "2026-09-04",
      usage30d: 46,
    },
    {
      id: "tp-2",
      name: "SLA proposal cover",
      channel: "email",
      category: "Sales",
      updatedAt: "2026-08-29",
      usage30d: 18,
    },
    {
      id: "tp-3",
      name: "Appointment reminder",
      channel: "sms",
      category: "Support",
      updatedAt: "2026-09-01",
      usage30d: 320,
    },
  ],
  team: [
    {
      id: "tm-1",
      name: "Malcolm Cuady",
      email: "malcolm@boundlessitsolutions.com",
      role: "Admin",
      openDeals: 2,
      closedWon30d: 210_000,
    },
    {
      id: "tm-2",
      name: "Rina Velasco",
      email: "rina@boundlessitsolutions.com",
      role: "Manager",
      openDeals: 1,
      closedWon30d: 0,
    },
    {
      id: "tm-3",
      name: "Jonas Park",
      email: "jonas@boundlessitsolutions.com",
      role: "Rep",
      openDeals: 1,
      closedWon30d: 0,
    },
    {
      id: "tm-4",
      name: "Aya Mendoza",
      email: "aya@boundlessitsolutions.com",
      role: "Marketing",
      openDeals: 1,
      closedWon30d: 0,
    },
  ],
  activities: [
    {
      id: "ac-1",
      type: "email",
      summary: "Elise Navarro replied on SLA first-response targets",
      actor: "Elise Navarro",
      at: "2026-09-11T08:40:00Z",
    },
    {
      id: "ac-2",
      type: "stage",
      summary: "Harborline omnichannel desk moved to Negotiation",
      actor: "Malcolm Cuady",
      at: "2026-09-10T11:15:00Z",
    },
    {
      id: "ac-3",
      type: "call",
      summary: "Discovery call with Priya Sundaram (Voltgrid)",
      actor: "Jonas Park",
      at: "2026-09-09T06:30:00Z",
    },
    {
      id: "ac-4",
      type: "task",
      summary: "Overdue: Re-engage stalled discovery (Voltgrid)",
      actor: "System",
      at: "2026-09-10T12:05:00Z",
    },
    {
      id: "ac-5",
      type: "note",
      summary: "Sofia Lim confirmed peak-season BPO window",
      actor: "Malcolm Cuady",
      at: "2026-09-10T13:20:00Z",
    },
  ],
});
